name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: legit
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: legit
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  no-cache:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: no
          tools: legit
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  key:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: legit
          key: v2
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
